version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
  build:
    commands:
      - echo Build started on `date`
      - mvn package -Dmaven.test.skip=true
#  post_build:
#    commands:
#      - echo Running tests for surefire junit
#      - mvn test #Running this task to execute unit tests and generate report.
#reports: #New
#  SurefireReports: # CodeBuild will create a report group called "SurefireReports".
#    files: #Store all of the files
#      - '**/*'
#    base-directory: 'target/surefire-reports' # Location of the reports 
artifacts:
  files:
    - target/spring-petclinic-2.2.0.BUILD-SNAPSHOT.jar
    - appspec.yml
    - scripts/runapp.sh
  discard-paths: yes
